36<div class="ppx-main-block" style="padding-left: 10%;">
 <h2>
  【Python 第36课】异常处理
 </h2>
 <br/>
 <p>
  在程序运行时，如果我们的代码引发了错误，python就会中断程序，并且输出错误提示。
 </p>
 <p>
 </p>
 <p>
  比如我们写了一句：
 </p>
 <p>
 </p>
 <pre class="language-python"><code>print (int('0.5'))</code></pre>
 <p>
 </p>
 <p>
  运行后程序得到错误提示：
 </p>
 <p>
 </p>
 <p>
  Traceback (most recent call last):
 </p>
 <p>
  File "C:/Python37/test.py", line 1, in &lt;module&gt;
 </p>
 <p>
  print (int('0.5'))
 </p>
 <p>
  ValueError: invalid literal for int() with base 10: '0.5'
 </p>
 <p>
 </p>
 <p>
  意思是，在test.py这个文件，第1行，print (int('0.5'))这里，你拿了一个不是10进制能够表示的字符，我没法把它转成int值。
 </p>
 <p>
 </p>
 <p>
  上面的错误可以避免，但在实际的应用中，有很多错误是开发者无法控制的，例如用户输入了一个不合规定的值，或者需要打开的文件不存在。这些情况被称作“异常”，一个好的程序需要能处理可能发生的异常，避免程序因此而中断。
 </p>
 <p>
 </p>
 <p>
  例如我们去打开一个文件：
 </p>
 <p>
 </p>
 <pre class="language-python"><code>f = open('non-exist.txt')
print ('File opened!')
f.close()</code></pre>
 <p>
 </p>
 <p>
  假如这个文件因为某种原因并没有出现在应该出现的文件夹里，程序就会报错：
 </p>
 <p>
 </p>
 <p>
  IOError: [Errno 2] No such file or directory: 'non-exist.txt'
 </p>
 <p>
 </p>
 <p>
  程序在出错处中断，后面的print不会被执行。
 </p>
 <p>
 </p>
 <p>
  在python中，可以使用try...except语句来处理异常。做法是，把可能引发异常的语句放在try-块中，把处理异常的语句放在except-块中。
 </p>
 <p>
 </p>
 <p>
  把刚才那段代码放入try...except中：
 </p>
 <p>
 </p>
 <pre class="language-python"><code>try:
   f = open('non-exist.txt')
   print ('File opened!')
   f.close()
except:
   print ('File not exists.')
print ('Done')</code></pre>
 <p>
 </p>
 <p>
  当程序在try内部打开文件引发异常时，会跳过try中剩下的代码，直接跳转到except中的语句处理异常。于是输出了“File not exists.”。如果文件被顺利打开，则会输出“File opened!”，而不会去执行except中的语句。
 </p>
 <p>
 </p>
 <p>
  但无论如何，整个程序不会中断，最后的“Done”都会被输出。
 </p>
 <p>
 </p>
 <p>
  在try...except语句中，try中引发的异常就像是扔出了一只飞盘，而except就是一只灵敏的狗，总能准确地接住飞盘。
 </p>
 <nav aria-label="...">
  <ul class="pager">
   <li class="previous">
    <a href="../36">
     <span aria-hidden="true">
      ←
     </span>
     35.continue
    </a>
   </li>
   <li class="next">
    <a href="../38">
     37.字典
     <span aria-hidden="true">
      →
     </span>
    </a>
   </li>
  </ul>
 </nav>
</div>
